# -*- coding: utf-8 -*-
"""Traffic_Crash_Severity_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnUJoHx07BXZcMDAxXxFN4k8rIFwPTgD

# Statistical Modeling of Traffic Crash Severity Using Logistic Regression

This project applies logistic regression as a statistical modeling technique to classify crash severity patterns across U.S. states.
"""

!pip install pandas numpy matplotlib seaborn scikit-learn --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

sns.set_style("whitegrid")

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/car_crashes.csv"
df = pd.read_csv(url)
df.head()

print("Shape:", df.shape)
print("\nMissing Values:\n", df.isnull().sum())
print("\nSummary Stats:\n", df.describe())

plt.figure(figsize=(8,5))
sns.histplot(df['speeding'], bins=10)
plt.title("Distribution of Traffic Counts")
plt.show()

df['high_severity'] = np.where(df['total'] > df['total'].median(), 1, 0)
df.head()

X = df.drop(['high_severity', 'abbrev'], axis=1)
y = df['high_severity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()